apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
spec:
  storageClassName: prometheus
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/prometheus/server/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-pv-1
spec:
  storageClassName: prometheus-alertmanager
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/prometheus/alertmanager/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server-pvc
spec:
  storageClassName: "prometheus"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
