apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-etcd-pv
spec:
  storageClassName: milvus
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/milvus/data/etcd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-minio-pv
spec:
  storageClassName: milvus
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/milvus/data/minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-volume-pv
spec:
  storageClassName: milvus
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/milvus/data/milvus