apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdg-server
  labels:
    app: imdg-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: imdg-server
  template:
    metadata:
      labels:
        app: imdg-server
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
      - name: {{ .name }}
{{- end }}
      containers:
      - name: imdg-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path }}
            port: {{ .Values.probes.liveness.port }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path }}
            port: {{ .Values.probes.readiness.port }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
