kind: ConfigMap
apiVersion: v1
metadata:
  name: imdg-server-cm
data:
  spring.mongodb.uri: mongodb+srv://${spring.mongodb.username}:${spring.mongodb.password}@${spring.mongodb.host}/${spring.mongodb.database}?retryWrites=true&w=majority
  spring.mongodb.host: 
  spring.mongodb.port: "27017"
  spring.mongodb.username: 