kind: ConfigMap
apiVersion: v1
metadata:
  name: imdg-chatbot-ui-cm
data:
  "IMDG_SERVER_URL": "http://imdg-server-service.imdg-server.svc.cluster.local"
  "MILVUS_URI": "http://milvus-standalone.milvus.svc.cluster.local:19530"
