global:
  imageRegistry: null

rbac:
  create: true

serviceAccount:
  create: true

replicas: 2

image:
  registry: docker.io
  repository: grafana/grafana
  tag: "13.1.0"

resources:
 limits:
   cpu: 1000m
   memory: 1Gi
 requests:
   cpu: 500m
   memory: 256Mi

persistence:
  type: pvc
  enabled: true
  existingClaim: "grafana-pvc"
  accessModes:
    - ReadWriteOnce
  size: 5Gi

adminUser: admin
adminPassword: admin  